In [6]:
import cosima_cookbook as cc
session = cc.database.create_session()
expt = '01deg_jra55v140_iaf_cycle4'

In [7]:
cc.querying.get_variables(session, expt)

,name,long_name,units,frequency,ncfile,cell_methods,# ncfiles,time_start,time_end
0,adic,natural + anthropogenic dissolved inorganic ca...,mmol/m^3,None,output904/ocean/oceanbgc-3d-adic-1-daily-mean-...,time: mean,3655,None,None
1,adic_int100,100m-integrated natural + anthropogenic dissol...,mmol/m^2,None,output931/ocean/oceanbgc-2d-adic_int100-1-dail...,time: mean,480,None,None
2,adic_intmld,MLD-integrated natural + anthropogenic dissolv...,mmol/m^2,None,output986/ocean/oceanbgc-2d-adic_intmld-1-dail...,time: mean,480,None,None
3,adic_xflux_adv,rho*dzt*dyt*u*tracer,kg/sec,None,output957/ocean/oceanbgc-3d-adic_xflux_adv-1-m...,time: mean,480,None,None
4,adic_yflux_adv,rho*dzt*dxt*v*tracer,kg/sec,None,output846/ocean/oceanbgc-3d-adic_yflux_adv-1-m...,time: mean,480,None,None
...,...,...,...,...,...,...,...,...,...
421,time,time,days since 1900-01-01 00:00:00,static,output991/ocean/ocean-2d-drag_coeff.nc,None,3900,1900-01-01 00:00:00,2019-01-01 00:00:00
422,xt_ocean,tcell longitude,degrees_E,static,output824/ocean/ocean-2d-area_t.nc,None,1820,1900-01-01 00:00:00,1900-01-01 00:00:00
423,xu_ocean,ucell longitude,degrees_E,static,output991/ocean/ocean-2d-drag_coeff.nc,None,2080,1900-01-01 00:00:00,2019-01-01 00:00:00
424,yt_ocean,tcell latitude,degrees_N,static,output824/ocean/ocean-2d-area_t.nc,None,1820,1900-01-01 00:00:00,1900-01-01 00:00:00
425,yu_ocean,ucell latitude,degrees_N,static,output991/ocean/ocean-2d-drag_coeff.nc,None,2080,1900-01-01 00:00:00,2019-01-01 00:00:00

In [8]:
cc.querying.getvar(expt, 'adic', session, n=-1)

VariableNotFoundError: No files were found containing 'adic' in the '01deg_jra55v140_iaf_cycle4' experiment